# All possible event types from github
ALLOWED_EVENT_TYPES = [
    "CreateEvent",
    "DeleteEvent",
    "DiscussionEvent",
    "ForkEvent",
    "GollumEvent",
    "IssueCommentEvent",
    "IssuesEvent",
    "MemberEvent",
    "PublicEvent",
    "PullRequestEvent",
    "PullRequestReviewEvent",
    "PullRequestReviewCommentEvent",
    "PushEvent",
    "ReleaseEvent",
    "WatchEvent",
]
# Repositories to ignore
IGNORE_REPOS = [
    "WardDeb/WardDeb"
]

# Wanted event types to display
[WANTED_EVENT_TYPES]
DiscussionEvent  = "ğŸ“£ contributed to discussion in"
ForkEvent        = "ğŸ¥„ forked"
IssuesEvent      = "ğŸ made/updated issue(s) in"
PublicEvent      = "ğŸ‰ released"
PullRequestEvent = "ğŸª¢ PR'ed to"
PushEvent        = "ğŸ«¸ pushed commit(s) to"
ReleaseEvent     = "ğŸ‰ released"

# File markers
[FILE_MARKERS]
start_marker = "<!--START_SECTION:raa-->"
end_marker   = "<!--END_SECTION:raa-->"
